//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetoesw3rd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int admins_id { get; set; }
        public string admins_name { get; set; }
        public System.DateTime admins_dob { get; set; }
        public int admins_country_id { get; set; }
        public string admins_email { get; set; }
        public string admins_password { get; set; }
        public string admins_role { get; set; }
    }
}
