//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetoesw3rd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int applications_id { get; set; }
        public int applications_user_id { get; set; }
        public int applications_university_id { get; set; }
        public int applications_mobility_program_id { get; set; }
        public string applications_status { get; set; }
        public bool applications_scholarship { get; set; }
    }
}
