//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetoesw3rd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Help
    {
        public int help_id { get; set; }
        public string help_message { get; set; }
        public string help_name { get; set; }
    }
}
