//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetoesw3rd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobilityProgram
    {
        public int mobilityprog_id { get; set; }
        public string mobilityprog_name { get; set; }
        public string mobilityprog_type { get; set; }
        public System.DateTime mobilityprog_init_date { get; set; }
        public System.DateTime mobilityprog_end_date { get; set; }
        public string mobilityprog_degree { get; set; }
        public byte mobilityprog_academic_year { get; set; }
        public byte mobilityprog_semester { get; set; }
    }
}
