//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetoesw3rd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int notifications_id { get; set; }
        public string notifications_subject { get; set; }
        public string notifications_text { get; set; }
        public int notifications_users_id { get; set; }
        public int notifications_admin_id { get; set; }
        public int notifications_events_id { get; set; }
    }
}
