//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetoesw3rd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class University
    {
        public int university_id { get; set; }
        public int university_country_id { get; set; }
        public string university_name { get; set; }
    }
}
