//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetoesw3rd.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        [Key]
        public int users_id { get; set; }
        [Display(Name = "Name")]
        public string users_name { get; set; }
        [Display(Name = "Number")]
        public int users_number { get; set; }
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        public string users_email { get; set; }
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string users_password { get; set; }
        [Display(Name = "Date of birth")]
        public System.DateTime users_dob { get; set; }
        [Display(Name = "Country")]
        public int users_country_id { get; set; }
        [Display(Name = "Credits")]
        public short users_credits { get; set; }
        [Display(Name = "diseases")]
        public string users_diseases { get; set; }
        [Display(Name = "Mobility")]
        public bool users_mobility { get; set; }
    }
}
